### ISSUE TITLE
display for refactor hints

### ISSUE THREAD

**Issue by psolvy** [pantajoe/vscode-elixir-credo#1]
Hello! your extension is great!

![image](https://user-images.githubusercontent.com/33094694/99940335-01d79680-2d7d-11eb-86a3-0c83c141ed16.png)

But why did choose not to display `Refactor` in problem list, and not to underline it in file? (https://github.com/pantajoe/vscode-elixir-credo/blob/main/src/CredoParser.ts#L28) As u can see on screen there is information about in credo output:

![image](https://user-images.githubusercontent.com/33094694/99940846-0d778d00-2d7e-11eb-824b-92e0fc31d823.png)

Also, on first screen there is underlining (TODO comment), when in credo output there is no start/end line column, it will be great to underline THE HOLE string in that case)

![image](https://user-images.githubusercontent.com/33094694/99941733-9511cb80-2d7f-11eb-9cc9-aeed5978ca58.png)

TY!

**Comment by pantajoe** [comment]
Hi @psolvy !
I'm glad the extension is useful to you.

This is how the severity for VSCode is currently parsed from the Credo Issues:
https://github.com/pantajoe/vscode-elixir-credo/blob/v0.0.5/src/CredoParser.ts#L23-L31

VSCode Diagnostics have 4 Levels:
* 0 = Error
* 1 = Warning
* 2 = Information
* 3= Hint

VSCode actually recommends displaying refactors as Hints. I didn't know though that Hints are neither displayed in the Problem list nor underlined. VSCode just displays those 3 yellow little dots instead, which are not at all visible.

Since I chose to display most categories as Information, I will change most categories to be displayed as Information or Warnings. Thanks for pointing out that interaction!

I'll work on both your remarks, and will notify you here in this issue as soon as a new version is released with those 2 features.

**Comment by pantajoe** [comment]
Hey there! :)
I published a new release of the extension.
I believe, it solves both your remarks which is why I will close this issue for now.
Feel free to reopen it if something goes wrong.
